---
- hosts: all
  become: yes
  tasks:
    - name: Install pip
      apt:
        state: present
        name: python3-pip
    - name: Install flask and gunicorn
      pip:
        name:
          - flask
          - gunicorn
    - name: Run gunicorn
      command: gunicorn -b 0.0.0.0:8080 --daemon --reload main:app
