---
- hosts: all
  become: yes
  tasks:
    - name: Install pip
      apt:
        state: present
        name: python3-pip
    - name: Install flask and gunicorn
      pip:
        name:
          - flask
          - gunicorn
